### ISSUE TITLE
Add "Donate" button to "Manufacture" and "Volunteer"

### ISSUE THREAD

**Issue by myastark** [CRASHSpace/covid.crashspace.org#16]
**Is your feature request related to a problem? Please describe.**
People may miss the small text only Donate option on top nav

**Describe the solution you'd like**
Add a button exactly like the other two, "Manufacture," "Volunteer," "Donate"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by danstepanov** [comment]
This link exists.

**Comment by danstepanov** [comment]
<img width="439" alt="Screen Shot 2020-05-22 at 1 13 07 PM" src="https://user-images.githubusercontent.com/5482800/82706198-fc628d80-9c2d-11ea-8f10-33e458beac55.png">
