### ISSUE TITLE
Copy edits required on About page

### ISSUE THREAD

**Issue by myastark** [CRASHSpace/covid.crashspace.org#5]
Under "Fundraising":
_We taking donations through_
should be
_We **are** taking donations through_

_as we mass produce, package, and distribute clinician evaluated_
should be
_as we mass-produce, package, and distribute clinician-evaluated_

Under "Our Healthcare Partners"

_a nexus of information sharing_
should be
_a nexus of information-sharing_

**Comment by knarx** [comment]
updated!
